### ISSUE TITLE
Super Mario Bros.

### ISSUE THREAD

**Issue by vada4367** [dayporol/alex-mario#1]
Здраствуй, dayporol. Сегодня, просматривая ваш код, я обнаружил один баг и несколько недоработок.

**Баги:**
1. При нахождении коллизии с грыбочками, ты смотришь всего лишь на один гриб, и он может быть мёртывым.
2. Если решить недоработку под номером 1, у тебя появится баг с коллизией. Он очень похож на баг под номером 1.
2. Если попытаться выбить монетку, и при этом коснуться обычного блока, ты не соберёшь монетку.

**Недоработки:**
1. В редакторе кода ты не можешь поставить большие блоки в ровный ряд, а соответственно и монетки.

**Как их можно решить:**
1. _При нахождении коллизии, делать цикл для каждого предмета, входящий в неё_.

### Таким образом, ты убиваешь двух зайцев.

**Так же я доработал твою игру, добавив следующие фишки:**

_1. Отскок от гриба при его убийстве.
2. Иннерцию при ходьбе.
3. Иннерцию при прыжке.
4. Новый уровень из оригинального марио.
5. Исправленный редактор.
6. Текстура монеток стала больше.
7. Исправленные размеры текстуры блоков._

Доброго вечера, dayporol.
Дорогой vada4367.

[newlevel.zip](https://github.com/dayporol/alex-mario/files/9133409/newlevel.zip)

[scripts.zip](https://github.com/dayporol/alex-mario/files/9133399/scripts.zip)
[textures.zip](https://github.com/dayporol/alex-mario/files/9133400/textures.zip)

**Comment by dayporol** [comment]
1. в конце ты пожелал счастливого вечера самому себе.
2. Баг с грибом мне нравился т.к. можно было сделать так что ты его
убиваешь а потом заставляет прыгать на своей голове.
3. инерцию ходьбы мы с папой сделали, но фишку с прыжком нет потому что она
меня раздражает.
4. Большие размеры блоков мне нравились побольше чем маленькие. Это
касается и монетки.

вс, 31 июл. 2022 г., 20:45 vada4367 ***@***.***>:

**Comment by dayporol** [comment]
А прости про 1 пункт неправда...


вс, 31 июл. 2022 г., 21:07 Smax Home ***@***.***>:
